module.exports = {
    NULL_VALUE: '필요한 값이 없습니다.',
    INVALID_TOKEN: '유효하지 않은 token 입니다.',
    EMPTY_TOKEN: '토큰값이 존재하지 않습니다.',
    EXPIRED_TOKEN: '만료된 토큰입니다.',
    EMPTY_REFRESH_TOKEN: '재발급 토큰이 존재하지 않습니다.',
    CREATE_TOKEN: '토큰 발급 완료.',
    REFRESH_TOKEN: '토큰 재발급 완료.',
    NO_SELECT_AUTHORITY: '조회 권한 없음.',
    USER_SELECTED: '회원 조회 성공.',
    SIGN_UP_INSERT_SUCCESS: '회원가입 성공',
    SIGN_IN_SUCCESS: '로그인 성공',
    SIGN_IN_ERROR: '잘못된 아이디 또는 비밀번호 입니다.',
    VALID_ID: '이용가능한 아이디',
    INVALID_ID: '중복되는 아이디',
    INSERT_FAILED: '등록 실패',
    INTERNAL_SERVER_ERROR: '서버 내부 에러',
    SUCCESS: 'success',
    DUPLICATED: 'duplicated',
    DB_ERROR: '데이터베이스 에러',
    CONTACT_APPEND_SUCCESS: '긴급전화 정보 등록 성공',
    CONTACT_DATA_LIST_SUCCESS: '긴급전화 리스트 가져오기 성공',
    RECORD_APPEND_SUCCESS: '녹음 정보 등록 성공',
    RECORD_DATA_LIST_SUCCESS: '녹음 리스트 가져오기 성공',
    VISITOR_DATA_LIST_SUCCESS: '방문자 리스트 가져오기 성공',
    VISITOR_APPEND_SUCCESS: '새로운 방문자 정보 등록 성공',
    VISITOR_MODIFY_SUCCESS: '방문자 정보 수정하기 성공',
    VISITOR_DETECT_SUCCESS: '방문자 목록에 존재하는 방문자입니다.',
    VISITOR_DETECT_FAIL: '방문자 목록에 존재하지 않는 방문자입니다.'
}
